# Introduction to NumPy

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

## Key Features of NumPy
- **N-Dimensional Arrays**: Efficient, multidimensional container for generic data.
- **Mathematical Functions**: Tools for operations such as algebra, calculus, and statistics.
- **Broadcasting**: Automatic expansion of arrays during arithmetic operations.
- **Integration with C/C++ and Fortran Code**: For high-performance computation.

---

## 1. Installing NumPy
To install NumPy, use the following command:
```bash
pip install numpy
```
## 2. Importing NumPy
The standard way to import NumPy is as follows:


In [1]:
import numpy as np

By convention, NumPy is imported with the alias np.

---

# Numpy Arrays
NumPy arrays are the core data structure provided by the NumPy library. They offer efficient storage and manipulation of numerical data in multiple dimensions. 


## 1. Creating Arrays

### From Python Lists
You can create a NumPy array from a Python list using the `np.array()` function.

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

### Using Built-in Functions
`np.zeros()`: Create an array filled with zeros

In [3]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`np.ones()`: Create an array filled with ones

In [4]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`np.arange()`: Create an array with evenly spaced values within a given range

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`np.linspace()`: Create an array with evenly spaced values between two points

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random 
`np.random.random()`: Create an array of random values between 0 and 1

In [7]:
np.random.random((2, 3))
# A 2x3 array of random values between 0 and 1

array([[0.86885876, 0.70688855, 0.77690528],
       [0.53119379, 0.98158324, 0.66415215]])

`np.random.randint()`: Create an array of random integers within a specified range

In [8]:
np.random.randint(1, 10, (3, 3))
# A 3x3 array of random integers between 1 and 9

array([[9, 5, 6],
       [7, 6, 5],
       [6, 3, 1]], dtype=int32)

## 2. Array Types
### 1D Arrays
One-dimensional arrays are simple arrays where data is stored in a single row.

In [9]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

### 2D Arrays
Two-dimensional arrays store data in a matrix (rows and columns).

In [10]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

### N-Dimensional Arrays
NumPy can handle arrays of arbitrary dimensions. For example, a 3D array (a cube of data) is created as follows:

In [11]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## 3. Array Data Types (dtype)
NumPy arrays can contain elements of a specific data type. You can either let NumPy infer the data type or specify it explicitly.

### Checking the Data Type
You can check the data type of a NumPy array using the .dtype attribute.

In [12]:
np.array([1, 2, 3])

array([1, 2, 3])

### Specifying the Data Type
You can specify the data type when creating a NumPy array by passing the dtype argument.

In [13]:
np.array([1, 2, 3], dtype='float64')

array([1., 2., 3.])

Common Data Types in NumPy:

- `int32`, `int64`: Integer types of different sizes.
- `float32`, `float64`: Floating-point numbers.
- `bool`: Boolean values (True or False).

---

# Array Indexing and Slicing

NumPy allows for efficient and flexible access to elements of arrays using indexing and slicing. These tools are essential for selecting, manipulating, and analyzing data within arrays.


## 1. Accessing Elements: Indexing

### 1D Array Indexing
You can access individual elements in a 1D array by specifying the index (starting from 0).

In [14]:
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d[2])

30


### 2D Array Indexing
In a 2D array (matrix), you can access elements by specifying the row and column index.

In [15]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr_2d[1, 2])  # Outputs: 60 (row 1, column 2)

60


### N-Dimensional Array Indexing
For arrays with more than two dimensions, you can use the same principle of specifying the index for each dimension.

In [16]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[1, 0, 1])  # Outputs: 6 (2nd group, 1st row, 2nd column)


6


---


## 2. Slicing: Extracting Subsets of Arrays
Slicing allows you to extract parts of an array by specifying a range of indices. The syntax is [start:end:step], where start is inclusive, and end is exclusive.

### 1D Array Slicing

In [17]:
arr_1d = np.array([10, 20, 30, 40, 50, 60])
print(arr_1d[1:4])  # Outputs: [20 30 40] (from index 1 to 3)

[20 30 40]


You can also use negative indices to slice from the end of the array:

In [18]:
print(arr_1d[-3:])  # Outputs: [40 50 60]


[40 50 60]


### 2D Array Slicing
In a 2D array, you can slice rows and columns by specifying ranges for both dimensions.

In [19]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr_2d[0:2, 1:3])  
# Outputs:
# [[20 30]
#  [50 60]]


[[20 30]
 [50 60]]


This extracts rows 0 and 1, and columns 1 and 2.

### Slicing with Steps
You can specify a step size to select elements at regular intervals.

In [20]:
arr_1d = np.array([10, 20, 30, 40, 50, 60])
print(arr_1d[::2])  # Outputs: [10 30 50] (every second element)


[10 30 50]


### 3. Boolean Indexing: Filtering Data
Boolean indexing allows you to filter arrays based on conditions. This creates a boolean mask (True/False) that selects elements based on the condition.

#### Example: Filter Values Greater Than 30

In [21]:
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[arr > 30]
print(filtered_arr)  # Outputs: [40 50]


[40 50]


#### Example: Combine Multiple Conditions
You can combine multiple conditions using logical operators (&, |, ~ for and, or, and not).

In [22]:
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr > 20) & (arr < 50)]
print(filtered_arr)  # Outputs: [30 40]


[30 40]


---

# Array Operations

NumPy provides powerful tools for performing element-wise operations on arrays, as well as more complex mathematical operations. Understanding how NumPy handles arithmetic, broadcasting, and mathematical functions is crucial for working with numerical data.

## 1. Basic Arithmetic Operations
NumPy allows for element-wise arithmetic operations on arrays. These operations work on arrays of the same shape, or on arrays that can be broadcasted to the same shape.

### Element-wise Addition


In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Outputs: [5 7 9]

[5 7 9]


### Element-wise Subtractionm

In [24]:
print(arr2 - arr1)  # Outputs: [3 3 3]

[3 3 3]


### Element-wise Multiplication

In [25]:
print(arr1 * arr2)  # Outputs: [4 10 18]


[ 4 10 18]


### Element-wise Division


In [26]:
print(arr2 / arr1)  # Outputs: [4.  2.5 2. ]


[4.  2.5 2. ]


## 2. Broadcasting
Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes. It expands the smaller array along the dimensions of the larger one, without making actual copies of data.

### Broadcasting Example

In [27]:
arr = np.array([1, 2, 3])
scalar = 10
print(arr + scalar)  # Outputs: [11 12 13] (scalar is added to each element)


[11 12 13]


### Broadcasting with 2D Arrays


In [28]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d + arr)  # Outputs:
# [[2 4 6]
#  [5 7 9]]


[[2 4 6]
 [5 7 9]]


The 1D array arr is broadcast across the rows of the 2D array arr_2d.

## 3. Mathematical Functions
Universal Functions (ufuncs)
NumPy provides a wide range of mathematical functions that operate element-wise on arrays, called universal functions or ufuncs.

### **Sum of elements:**

In [29]:
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  # Outputs: 10


10


### **Mean of elements:**

In [30]:
print(np.mean(arr))  # Outputs: 2.5


2.5


### **Median of elements:**

In [31]:
print(np.median(arr))  # Outputs: 2.5


2.5


### **Standard Deviation:**

In [32]:
print(np.std(arr))  # Outputs: 1.118033988749895


1.118033988749895


### **Variance:**

In [33]:
print(np.var(arr))  # Outputs: 1.25


1.25


## 4. Trigonometric Functions
NumPy provides a set of trigonometric functions that work element-wise on arrays.

**Example: Sine Function**

In [34]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # Outputs: [0. 1. 0.]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


**Example: Cosine Function**

In [35]:
print(np.cos(angles))  # Outputs: [ 1. 0. -1.]


[ 1.000000e+00  6.123234e-17 -1.000000e+00]


## 5. Exponential and Logarithmic Functions
NumPy also includes functions for exponentiation and logarithmic calculations.

**Exponential Function**

In [36]:
arr = np.array([1, 2, 3])
print(np.exp(arr))  # Outputs: [ 2.71828183  7.3890561  20.08553692]


[ 2.71828183  7.3890561  20.08553692]


**Logarithmic Function**

In [37]:
arr = np.array([1, np.e, np.e**2])
print(np.log(arr))  # Outputs: [0. 1. 2.]


[0. 1. 2.]


---

# Array Manipulation

NumPy provides various tools for reshaping, concatenating, stacking, and splitting arrays. These operations allow you to transform and manage the layout of your data efficiently.

## 1. Reshaping Arrays
Reshaping allows you to change the shape of an array without changing its data. NumPy provides several functions to accomplish this.

### `reshape()`: Changing the shape of an array
The `reshape()` function is used to change the shape of an array to the desired dimensions, as long as the total number of elements remains the same.

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# Outputs:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


### `ravel():` Flattening an array to 1D

The `ravel()` function returns a flattened 1D array without making a copy of the data (if possible).

In [39]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr_2d.ravel()
print(flattened_arr)  # Outputs: [1 2 3 4 5 6]

[1 2 3 4 5 6]


### `flatten()`: Flattening an array to 1D

Unlike `ravel()`, `flatten()` always returns a copy of the array.

In [40]:
flattened_arr = arr_2d.flatten()
print(flattened_arr)  # Outputs: [1 2 3 4 5 6]


[1 2 3 4 5 6]


## 2. Concatenation and Stacking
### `np.concatenate()`: Concatenating arrays along an axis
You can concatenate arrays along different axes using `np.concatenate()`.

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))
print(concatenated)  # Outputs: [1 2 3 4 5 6]


[1 2 3 4 5 6]


### `np.vstack()`: Vertical stacking (row-wise)

`vstack()` stacks arrays vertically, treating each input array as a row.

In [42]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_vertically = np.vstack((arr1, arr2))
print(stacked_vertically)
# Outputs:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


### `np.hstack()`: Horizontal stacking (column-wise)

`hstack()` stacks arrays horizontally, treating each input array as a column.

In [43]:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4], [5], [6]])
stacked_horizontally = np.hstack((arr1, arr2))
print(stacked_horizontally)
# Outputs:
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


## 3. Splitting Arrays
Splitting allows you to break an array into multiple sub-arrays.

### `np.split()`: Splitting an array into multiple sub-arrays
`split()` divides an array into multiple sub-arrays at the specified indices.

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Split into 3 equal parts
print(split_arr)  # Outputs: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]


### `np.hsplit()`: Horizontal split

`hsplit()` splits an array horizontally (column-wise) into multiple sub-arrays.

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
split_arr = np.hsplit(arr, 3)  # Split into 3 parts along the columns
print(split_arr)
# Outputs:
# [array([[1],
#         [4]]),
#  array([[2],
#         [5]]),
#  array([[3],
#         [6]])]


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


### `np.vsplit()`: Vertical split

`vsplit()` splits an array vertically (row-wise) into multiple sub-arrays.

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
split_arr = np.vsplit(arr, 2)  # Split into 2 parts along the rows
print(split_arr)
# Outputs:
# [array([[1, 2, 3]]),
#  array([[4, 5, 6]])]


[array([[1, 2, 3]]), array([[4, 5, 6]])]
