# Introduction to NumPy

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

## Key Features of NumPy
- **N-Dimensional Arrays**: Efficient, multidimensional container for generic data.
- **Mathematical Functions**: Tools for operations such as algebra, calculus, and statistics.
- **Broadcasting**: Automatic expansion of arrays during arithmetic operations.
- **Integration with C/C++ and Fortran Code**: For high-performance computation.

---

## 1. Installing NumPy
To install NumPy, use the following command:
```bash
pip install numpy
```
## 2. Importing NumPy
The standard way to import NumPy is as follows:


In [1]:
import numpy as np

By convention, NumPy is imported with the alias np.

# Numpy Arrays
NumPy arrays are the core data structure provided by the NumPy library. They offer efficient storage and manipulation of numerical data in multiple dimensions. 

---

## 1. Creating Arrays

### From Python Lists
You can create a NumPy array from a Python list using the `np.array()` function.

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

### Using Built-in Functions
`np.zeros()`: Create an array filled with zeros

In [3]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`np.ones()`: Create an array filled with ones

In [4]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`np.arange()`: Create an array with evenly spaced values within a given range

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`np.linspace()`: Create an array with evenly spaced values between two points

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random 
`np.random.random()`: Create an array of random values between 0 and 1

In [7]:
np.random.random((2, 3))
# A 2x3 array of random values between 0 and 1

array([[0.15319864, 0.66170929, 0.07364881],
       [0.33640374, 0.48868317, 0.91510097]])

`np.random.randint()`: Create an array of random integers within a specified range

In [8]:
np.random.randint(1, 10, (3, 3))
# A 3x3 array of random integers between 1 and 9

array([[2, 4, 7],
       [3, 3, 1],
       [7, 4, 4]], dtype=int32)

---

## 2. Array Types
### 1D Arrays
One-dimensional arrays are simple arrays where data is stored in a single row.

In [9]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

### 2D Arrays
Two-dimensional arrays store data in a matrix (rows and columns).

In [10]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

### N-Dimensional Arrays
NumPy can handle arrays of arbitrary dimensions. For example, a 3D array (a cube of data) is created as follows:

In [11]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

---

## 3. Array Data Types (dtype)
NumPy arrays can contain elements of a specific data type. You can either let NumPy infer the data type or specify it explicitly.

### Checking the Data Type
You can check the data type of a NumPy array using the .dtype attribute.

In [12]:
np.array([1, 2, 3])

array([1, 2, 3])

### Specifying the Data Type
You can specify the data type when creating a NumPy array by passing the dtype argument.

In [13]:
np.array([1, 2, 3], dtype='float64')

array([1., 2., 3.])

Common Data Types in NumPy:

- `int32`, `int64`: Integer types of different sizes.
- `float32`, `float64`: Floating-point numbers.
- `bool`: Boolean values (True or False).

# Array Indexing and Slicing

NumPy allows for efficient and flexible access to elements of arrays using indexing and slicing. These tools are essential for selecting, manipulating, and analyzing data within arrays.

---

## 1. Accessing Elements: Indexing

### 1D Array Indexing
You can access individual elements in a 1D array by specifying the index (starting from 0).

In [19]:
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d[2])

30


### 2D Array Indexing
In a 2D array (matrix), you can access elements by specifying the row and column index.

In [20]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr_2d[1, 2])  # Outputs: 60 (row 1, column 2)

60


### N-Dimensional Array Indexing
For arrays with more than two dimensions, you can use the same principle of specifying the index for each dimension.

In [21]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[1, 0, 1])  # Outputs: 6 (2nd group, 1st row, 2nd column)


6


---


## 2. Slicing: Extracting Subsets of Arrays
Slicing allows you to extract parts of an array by specifying a range of indices. The syntax is [start:end:step], where start is inclusive, and end is exclusive.

### 1D Array Slicing